### ISSUE TITLE
Add human-readable list of countries

### ISSUE THREAD

**Issue by rugk** [ENT8R/blacklistr#5]
From https://github.com/westnordost/StreetComplete/pull/824#issuecomment-362792259:

> to make it really easy you could also automatically generate the alt/title text, which should list the countries and the quest's state there.

Actually you already have it mostly. You have the list on the right. Now it would only be useful if you can show this list in a human-readable way.

This can then be used as a text-description of the black- or whitelist this is generating. As said, this is useful for the alt and title text for the image in the wiki (https://github.com/ENT8R/blacklistr/issues/2).

**Comment by ENT8R** [comment]
So you want that something like this will be generated automatically:
```yaml
DE: whitelisted
US: blacklisted
DK: whitelisted
```
or:
```yaml
Germany: whitelisted
USA: blacklisted
Denmark: whitelisted
```
